### ISSUE TITLE
 Error inside first pull request - Received HTML instead of JSON

### ISSUE THREAD

**Issue by jamie-emb** [AstroCB/Messenger-CLI#11]
` info login Logging in...
info login Logged in
info login Request to reconnect
info login Request to pull 1
ERR! login Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.
{
  error: 'Error inside first pull request. Received HTML instead of JSON. Logging in inside a browser might help fix this.' `

Error when attempting to login, logged in inside browser. Cleared credentials are attempted again and still get the same error.

**Comment by AstroCB** [comment]
Hi, this issue can be monitored here: Schmavery/facebook-chat-api#794
