### ISSUE TITLE
Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response. 

### ISSUE THREAD

**Issue by JosephBBa** [AstroCB/Messenger-CLI#12]
@AstroCB  Maybe it's not the same error #9 , this is what happened after login in (node index,js),

ERR! listen Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response. ERR! listen at /root/node_modules/facebook-chat-api/utils.js:1042:15 ERR! listen at tryCatcher
ERR! listen at.. 
ERR! listen at..

Any changes can I do? A simple explanation, please.

**Comment by AstroCB** [comment]
Needed to bump some dependencies, but this is fixed in 6188afb37007c0f7bbccc7f97bd97922c3d01b4c.

A pull and an `npm install` should have you up and running.

Thanks!

**Comment by JosephBBa** [comment]
@AstroCB Thank you in advance for your support

![Fbmessage](https://user-images.githubusercontent.com/53361333/79254425-8f432780-7e39-11ea-840c-e5de84643345.png)

Does this Messenger-CLI able to send direct messages? which mean (ability to send a message to Recent(49) messages, not to Message Requests(1))
 Or require to be a friend.

**Comment by AstroCB** [comment]
I believe the way that Messenger works is that, if you are friends with the person, the message will be sent directly. If you’re not friends with them, it becomes a message request.

**Comment by JosephBBa** [comment]
But what about this api [api.sendDirectMessage](https://www.npmjs.com/package/facebook-chat-api/v/0.2.1#sendDirectMessage) 
it needs some modifications?

**Comment by AstroCB** [comment]
That function appears to be deprecated. I'm not sure what you're asking exactly – does sending messages with the CLI not work for you?

**Comment by JosephBBa** [comment]
I thought it was doing what I needed, but unfortunately, it didn't fulfill my goal.
If you have any idea about [DM](https://github.com/AstroCB/Messenger-CLI/issues/12#issuecomment-613578225) please tell me.

**Comment by AstroCB** [comment]
If I understand you correctly, you're trying to subvert message requests for people you're not friends with. I'm afraid that this is not possible even through the regular Facebook interface, as a security measure.

**Comment by JosephBBa** [comment]
[Exactly, ](https://www.facebook.com/davidm/posts/10156280061830195)
Thank you so much.

**Comment by Anh76PC** [comment]
@AstroCB  Can I ask you something?
