### ISSUE TITLE
Does it support messages to/from pages?

### ISSUE THREAD

**Issue by egils-consulting** [AstroCB/Messenger-CLI#15]

**Comment by AstroCB** [comment]
Yep! Sending messages to pages should be the same as sending them to people.

If you want to send a message _as_ a page, that'll take a little bit more effort. You'll have to change this line:

https://github.com/AstroCB/Messenger-CLI/blob/ae614c6ecccdd035e9eb97432f2a9120ed12e91d/index.js#L113

to include the ID of the page. It'd look like this:

```js
api.setOptions({ "logLevel": "warn", "listenEvents": true, "pageID": "YOUR_PAGE_ID" }); 
```

**Comment by egils-consulting** [comment]
Perfect! Thanks 😃
