### ISSUE TITLE
Sending a file

### ISSUE THREAD

**Issue by egils-consulting** [AstroCB/Messenger-CLI#16]
Hi. Does it support sending a file? I sometimes need to send a file.

How would I go about doing that? It does not have to be from the standard interface as it is not that often I need it.
I can probably code it myself, but if you can point me in the right direction it would be nice 😀

**Comment by AstroCB** [comment]
It does support sending a file. You can see all of the special commands [here](https://github.com/AstroCB/Messenger-CLI#special-commands).

To send a file, you'd include `{file|/path/to/file}` somewhere in your message, and it will be attached when you send it.

**Comment by egils-consulting** [comment]
Sorry for not reading the whole readme before asking. Yhe syntax you mention seems to differ from the one in yhe readme.

**Comment by AstroCB** [comment]
No worries, good luck!

**Comment by egils-consulting** [comment]
I looked closer at the code. Thanks for all the nice comments that make it crystal clear whats going on 👍
