### ISSUE TITLE
Feature Request: Friend List

### ISSUE THREAD

**Issue by Qualitymix** [AstroCB/Messenger-CLI#2]
It would be fantastic to have a command that listed the top X most recent chats.   This way I can see who I've chatted with recently and load: their chat.

**Comment by AstroCB** [comment]
This is a good idea; I'm going to look into maybe changing up the syntax a little bit to better accommodate these non-message commands.

**Comment by Qualitymix** [comment]
I've dove (diven?) into the source code, and have been messing around with getFriendsList.js     I'm not too familiar with the entire API but I'm getting closer I think.    I see that when you use load: to post the history of a thread,  you're stepping through 10 times , using the variable i as the incrementor.  

Doing this using the getFriendsList function doesn't work quite as nicely, but I'm sure I'm missing something.  I can't quite seem to get the callback function right.,

**Comment by AstroCB** [comment]
The load command in particular was added by @ameerthehacker in PR #1, so I hadn't looked at that too closely, but it looks like he's using getThreadHistory to load the last few messages from the thread and then stepping through all the messages returned by it.

I wouldn't use getFriendsList for this; perhaps [getThreadList](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadList) would be more useful if you're looking to pull the most recent conversations.

**Comment by Qualitymix** [comment]
Yes,  I'm currently working on using getThreadList.   I'm not familiar with JS or this API,  but the code is simple and thankfully all very well documented.   Hopefully I can throw something your way that will save you or anyone else for that matter some time in implementing something like this.

**Comment by Qualitymix** [comment]
I've got a working prototype for a command called list:
How do I submit it?

**Comment by AstroCB** [comment]
If you fork this repository and commit the change, you should be able to submit a pull request from your forked repo to this one.

**Comment by Qualitymix** [comment]
Done,  I think.   I thought I'd done it earlier, but I accidentally made a PR on my own repo lol
